version: '3'
name: 'madagasikara-soa'
services:
  hunspell:
    build:
      context: .
      dockerfile: Dockerfile
    image: hunspellmg
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8090:3000
      - 8091:80
      - 8092:8080
    working_dir: /var/www/html/themes/syntax-ts
    volumes:
      - ./www:/var/www/html
#    command: tail -F anything
    command: npm run dev
